apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: manojkr999/todo-next-app:c575153480261060d85ca6be8bc1c6ec9a2b0920
      ports:
        - containerPort: 80

