apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: manojkr999/todo-next-app:20a420175b21a220ef6b177eff31bfa6df4cf1ef
      ports:
        - containerPort: 80

